import './globals.css'
import './styles/prism-dracula.css';
import './styles/prism-custom.css';

import Nav from './components/nav'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="container px-8 mx-auto xl:px-5 max-w-screen-xl py-5 lg:py-8">
          <Nav></Nav>
        </div>
        {children}
      </body>
    </html>
  )
}
